version: '3.4'

services:
  simulator:
    image: iot-sim
    container_name: iot-sim
    build:
        context: ./simulator
    restart: always
    volumes:
      - ./simulator:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    networks:
      - middleware

  ui:
    image: iot-sim.ui
    container_name: iot-sim.ui
    build:
      context: ./ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000

  middleware:
    image: iot-sim.middleware
    container_name: iot-sim.middleware
    build:
      context: ./middleware
    ports:
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 15671:15671
      - 15672:15672
      - 1883:1883
    volumes:
      - "./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "./middleware/definitions.json:/etc/rabbitmq/definitions.json:ro"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - middleware

networks:
  middleware:
    driver: bridge
