[[replacers]]
input = { href = "/things/thermometer/properties/temperature", suppress = false }

[[replacers.outputs]]
value = 90
href = "/things/thermometer/properties/humidity"
delay = 2

[[replacers.outputs]]
value = 20
