[[replacers]]
input = { href = "/things/thermometer", property="temperature", suppress = false }

[[replacers.outputs]]
value = 90
href = "/things/thermometer"
property = "humidity"
delay = 2

[[replacers.outputs]]
value = 20
