[[proxies]]
input = { href = "/things/thermometer/properties/temperature", suppress = false }

[[proxies.outputs]]
value = 90
href = "/things/thermometer/properties/humidity"
delay = 2

[[proxies.outputs]]
value = 20