[[replacers]]
input = { href = "/things/thermometer", property = "temperature", suppress = true }

[[replacers.outputs]]
expr = "value > 23 ? 23 : value"
href = "/things/thermometer"
property = "temperature"
delay = 2
